#!/usr/bin/env python3
"""Convert a video into a 1-bit frame dump + C header for the BadApple animation.

Pipeline:
  1. ffmpeg resizes the video to the matrix size and extracts grayscale
     frames at the target framerate.
  2. Each pixel is thresholded to 1 bit (black/white).
  3. Frames are bit-packed (column-major, MSB first — see below) and written
     to a binary file.
  4. xxd -i turns the binary into a C array, and this script wraps it with
     metadata constants into a single generated header.

Bit packing (must match BadApple::step in src/animation.cpp):
  pixel index i = col * height + row  (column-major, like the matrix blob)
  byte = frame[i / 8], bit = 7 - (i % 8)  (MSB first)

Usage:
  make_badapple.py [INPUT] [--width N] [--height N] [--fps N] [--out PATH]

Defaults match the current matrix config (4 cols x 60 rows, 24 fps).
"""

import argparse
import math
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input", nargs="?", default=os.path.join(HERE, "badapple.mov"),
                   help="input video (default: badapple.mov next to this script)")
    p.add_argument("--width", type=int, default=4, help="matrix columns")
    p.add_argument("--height", type=int, default=15, help="matrix rows")
    p.add_argument("--fps", type=int, default=24, help="frames per second to extract")
    p.add_argument("--threshold", type=int, default=127,
                   help="grayscale threshold 0..255; above -> white (default 127)")
    p.add_argument("--out", default=os.path.join(REPO_ROOT, "include", "generated", "badapple_video.hpp"),
                   help="generated header path")
    p.add_argument("--preview", metavar="PREFIX",
                   help="also write watchable preview videos: PREFIX_gray.mp4 "
                        "(resized) and PREFIX_bw.mp4 (after threshold, i.e. exactly "
                        "what the LEDs will show), upscaled 20x with nearest neighbor")
    return p.parse_args()


def extract_gray_frames(args):
    """Run ffmpeg, return the raw grayscale byte stream (w*h bytes per frame)."""
    cmd = [
        "ffmpeg", "-v", "error", "-i", args.input,
        "-vf", f"fps={args.fps},scale={args.width}:{args.height}:flags=lanczos,format=gray",
        "-f", "rawvideo", "-pix_fmt", "gray", "-",
    ]
    return subprocess.run(cmd, check=True, capture_output=True).stdout


def make_previews(args):
    """Render the intermediate pipeline stages as watchable videos."""
    scale_down = f"fps={args.fps},scale={args.width}:{args.height}:flags=lanczos,format=gray"
    upscale = f"scale={args.width * 20}:{args.height * 20}:flags=neighbor"
    threshold = f"lut=y='if(gt(val,{args.threshold}),255,0)'"

    for name, vf in [("gray", f"{scale_down},{upscale}"),
                     ("bw", f"{scale_down},{threshold},{upscale}")]:
        out = f"{args.preview}_{name}.mp4"
        subprocess.run(["ffmpeg", "-y", "-v", "error", "-i", args.input,
                        "-vf", vf, "-pix_fmt", "yuv420p", out], check=True)
        print(f"preview:     {out}")


def pack_frames(raw, args):
    """Threshold and bit-pack; returns (dump bytes, frame_count, frame_bytes).

    ffmpeg emits frames ROW-major (i = y * width + x); the firmware expects
    COLUMN-major bits (i = col * height + row), so remap while packing.
    """
    pixels_per_frame = args.width * args.height
    frame_count = len(raw) // pixels_per_frame
    if frame_count == 0:
        sys.exit("error: no frames decoded (check input video and dimensions)")

    frame_bytes = (pixels_per_frame + 7) // 8
    dump = bytearray()
    for f in range(frame_count):
        frame = raw[f * pixels_per_frame:(f + 1) * pixels_per_frame]
        packed = bytearray(frame_bytes)
        for y in range(args.height):
            for x in range(args.width):
                if frame[y * args.width + x] > args.threshold:
                    i = x * args.height + y
                    packed[i // 8] |= 1 << (7 - (i % 8))
        dump += packed
    return bytes(dump), frame_count, frame_bytes


def generate_header(dump, frame_count, frame_bytes, args):
    """xxd -i the dump, then wrap it with metadata into one header."""
    with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as tmp:
        tmp.write(dump)
        tmp_path = tmp.name
    try:
        xxd = subprocess.run(["xxd", "-i", "-n", "badapple_video", tmp_path],
                             check=True, capture_output=True, text=True).stdout
    finally:
        os.unlink(tmp_path)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// GENERATED by helpers/bad_apple/make_badapple.py — do not edit by hand.\n")
        f.write(f"// Source: {os.path.basename(args.input)}, "
                f"{args.width}x{args.height} @ {args.fps} fps, 1 bit/pixel, threshold {args.threshold}.\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace badapple {\n")
        f.write(f"constexpr uint32_t width = {args.width};       // matrix columns\n")
        f.write(f"constexpr uint32_t height = {args.height};      // matrix rows\n")
        f.write(f"constexpr uint32_t frameCount = {frame_count};\n")
        f.write(f"constexpr uint32_t fps = {args.fps};\n")
        f.write(f"constexpr uint32_t frameBytes = {frame_bytes};  // (w*h+7)/8, MSB-first, column-major\n")
        f.write("} // namespace badapple\n\n")
        f.write(xxd)
    return frame_count


def main():
    args = parse_args()
    if not os.path.isfile(args.input):
        sys.exit(f"error: input video not found: {args.input}")

    raw = extract_gray_frames(args)
    dump, frame_count, frame_bytes = pack_frames(raw, args)
    generate_header(dump, frame_count, frame_bytes, args)
    if args.preview:
        make_previews(args)

    seconds = frame_count / args.fps
    print(f"frames:      {frame_count} ({seconds:.1f} s @ {args.fps} fps)")
    print(f"binary:      {len(dump)} bytes ({len(dump) / 1024:.1f} KiB, {frame_bytes} B/frame)")
    print(f"header:      {args.out} ({os.path.getsize(args.out) / 1024:.0f} KiB)")


if __name__ == "__main__":
    main()
